# -*- coding: utf-8 -*-
"""
04_visualization_figures.py

Publication-quality figure generation script.

Environmental niche differentiation of migratory bird stopover sites
revealed by remote sensing and explainable machine learning

This script reproduces the final publication figures using outputs
generated by:

01_data_preparation.py
02_multivariate_statistics.py
03_random_forest_shap_analysis.py

Author:
Likai Lin
Yan Gui
"""

import os
import warnings

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

warnings.filterwarnings("ignore")

# =====================================================
# paths
# =====================================================

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")

STAT_DIR = os.path.join(OUTPUT_DIR, "statistics")

RF_DIR = os.path.join(OUTPUT_DIR, "rf_shap")

FIG_DIR = os.path.join(BASE_DIR, "figures")

os.makedirs(FIG_DIR, exist_ok=True)

# =====================================================
# style
# =====================================================

plt.rcParams["font.family"] = "Times New Roman"

plt.rcParams["axes.linewidth"] = 0.8

plt.rcParams["figure.dpi"] = 300

sns.set_style("whitegrid")

# =====================================================
# helper
# =====================================================

def savefig(name):

    plt.savefig(
        os.path.join(FIG_DIR, name),
        dpi=600,
        bbox_inches="tight"
    )

    plt.close()


# =====================================================
# Figure 3
# PCA niche space
# =====================================================

print("Generating Figure 3...")

pca_file = os.path.join(
    STAT_DIR,
    "pca_scores.csv"
)

if os.path.exists(pca_file):

    df = pd.read_csv(pca_file)

    plt.figure(figsize=(7,6))

    sns.scatterplot(
        data=df,
        x="PC1",
        y="PC2",
        hue="functional_group",
        alpha=0.55,
        s=18
    )

    plt.xlabel("PC1")

    plt.ylabel("PC2")

    plt.title(
        "Environmental niche space",
        loc="left",
        fontweight="bold"
    )

    savefig("Figure3_PCA_niche_space.png")


# =====================================================
# Figure 4
# Variable importance
# =====================================================

print("Generating Figure 4...")

importance_file = os.path.join(
    RF_DIR,
    "rf_permutation_importance.csv"
)

if os.path.exists(importance_file):

    imp = pd.read_csv(importance_file)

    imp = imp.sort_values(
        "importance_mean",
        ascending=True
    )

    plt.figure(figsize=(6,5))

    plt.barh(
        imp["label"],
        imp["importance_mean"]
    )

    plt.xlabel(
        "Permutation importance"
    )

    plt.title(
        "Random forest variable importance",
        loc="left",
        fontweight="bold"
    )

    savefig("Figure4_RF_importance.png")


# =====================================================
# Figure 5
# SHAP summary
# =====================================================

print("Generating Figure 5...")

shap_file = os.path.join(
    RF_DIR,
    "shap_mean_importance.csv"
)

if os.path.exists(shap_file):

    shap_df = pd.read_csv(shap_file)

    shap_df = shap_df.sort_values(
        "mean_abs_shap",
        ascending=True
    )

    plt.figure(figsize=(6,5))

    plt.barh(
        shap_df["label"],
        shap_df["mean_abs_shap"]
    )

    plt.xlabel(
        "Mean |SHAP value|"
    )

    plt.title(
        "SHAP-based global feature contributions",
        loc="left",
        fontweight="bold"
    )

    savefig("Figure5_SHAP_summary.png")


# =====================================================
# Figure 6
# dependence plots
# =====================================================

print("Generating Figure 6...")

shap_values_file = os.path.join(
    RF_DIR,
    "shap_values_for_plotting.csv"
)

if os.path.exists(shap_values_file):

    df = pd.read_csv(
        shap_values_file
    )

    dependence_vars = [

        "log_ntl_2023",

        "lst_night_mean_c",

        "elevation_m",

        "water_occurrence"

    ]

    for var in dependence_vars:

        shap_col = f"SHAP_{var}"

        if shap_col not in df.columns:
            continue

        plt.figure(figsize=(4,3))

        plt.scatter(
            df[var],
            df[shap_col],
            s=8,
            alpha=0.45
        )

        plt.axhline(
            0,
            ls="--",
            lw=0.8,
            color="gray"
        )

        plt.xlabel(var)

        plt.ylabel("SHAP value")

        plt.title(
            f"Dependence on {var}",
            loc="left"
        )

        savefig(
            f"Figure6_dependence_{var}.png"
        )


# =====================================================
# Figure 7
# correlation heatmap
# =====================================================

print("Generating Figure 7...")

clean_file = os.path.join(
    OUTPUT_DIR,
    "analysis_dataset_clean.csv"
)

if os.path.exists(clean_file):

    df = pd.read_csv(clean_file)

    candidate_vars = [

        "log_ntl_2023",

        "cropland_frac",

        "elevation_m",

        "lst_night_mean_c",

        "log_pop_density_2020",

        "ndvi_mean",

        "forest_frac",

        "tree_frac",

        "wetland_frac"

    ]

    candidate_vars = [
        v
        for v in candidate_vars
        if v in df.columns
    ]

    corr = df[
        candidate_vars
    ].corr(
        method="spearman"
    )

    plt.figure(figsize=(7,6))

    sns.heatmap(
        corr,
        cmap="RdBu_r",
        center=0,
        square=True,
        annot=True,
        fmt=".2f"
    )

    plt.title(
        "Correlations among major predictors",
        loc="left",
        fontweight="bold"
    )

    savefig(
        "Figure7_correlation_heatmap.png"
    )

# =====================================================
# summary
# =====================================================

with open(
    os.path.join(
        FIG_DIR,
        "figure_generation_log.txt"
    ),
    "w",
    encoding="utf-8"
) as f:

    f.write(
        "Figure generation completed.\n"
    )

print(
    "\nAll figures generated successfully."
)

print(
    f"Output folder: {FIG_DIR}"
)
